language: python
python:
  - "3.5"
cache: pip
addons:
  apt:
    packages:
    - gdal-bin
    - libgdal-dev
    - libproj-dev
    - libgeos-dev
env:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal
install:
  - pip install -r requirements.txt
script:
  - python rhino-test.py